import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './components/NavBar'
import ThemeProvider from '../providers/ThemeProvider'
import QueryClientProvider from '@/providers/QueryClientProvider'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <ThemeProvider>
          <QueryClientProvider>
            <NavBar />
            <main className='container mx-auto px-4'>
              {children}
            </main>
          </QueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
